environment:
  MYSQL_DATABASE: test
  MYSQL_HOST: localhost
  MYSQL_USER: root
  MYSQL_PASSWORD: Password12!
  MYSQL_PATH: C:\Program Files\MySQL\MySQL Server 5.7

  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "4.4"
    - nodejs_version: "5.11"
    - nodejs_version: "6.2"


services:
  - mysql

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

before_test:
  - SET PATH=%MYSQL_PATH%\bin;%PATH%
  - mysqladmin --host=%MYSQL_HOST% --user=%MYSQL_USER% --password=%MYSQL_PASSWORD% create %MYSQL_DATABASE%

test_script:
  - mysql --version
  - node --version
  - npm --version
  - node test/run.js
  - SET MYSQL_USE_COMPRESSION=1
  - node test/run.js

version: "{build}"
