environment:
  MYSQL_DATABASE: test
  MYSQL_HOST: localhost
  MYSQL_USER: root
  MYSQL_PASSWORD: Password12!
  MYSQL_PATH: C:\Program Files\MySQL\MySQL Server 5.7
  LINT: 0

  matrix:
    - nodejs_version: '11'
      LINT: 0
    - nodejs_version: '12'
      LINT: 0
    - nodejs_version: '13'
      LINT: 1
    - nodejs_version: '14'
      LINT: 1

services:
  - mysql

cache:
  - node_modules
  - '%LOCALAPPDATA%/Yarn'

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

build: off

before_test:
  - SET PATH=%MYSQL_PATH%\bin;%PATH%
  - mysqladmin --host=%MYSQL_HOST% --user=%MYSQL_USER% --password=%MYSQL_PASSWORD% create %MYSQL_DATABASE%

test_script:
  - mysql --version
  - if "%LINT%"=="1" (yarn run lint)
  - node test/run.js
  - SET MYSQL_USE_COMPRESSION=1
  - node test/run.js

version: '{build}'
